spring:
  application:
    name: Project-API
  datasource:
    url: jdbc:h2:mem:produtos
    username: davi # sa -> username padrão
    password: 1212
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console #url padrão do H2